using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MovePlayer : MonoBehaviour
{
    public Rigidbody2D rb; 

    void Update()
    {
        if (Input.GetKey(KeyCode.A))
        {
            rb.velocity= new Vector2(-5,rb.velocity.y);
            
        }

        if (Input.GetKey(KeyCode.S))
        { 
        }
        
        if (Input.GetKey(KeyCode.D)) 
        {
            rb.velocity = new Vector2(5, rb.velocity.y);
           
        }
        
        if (Input.GetKey(KeyCode.Space))
        {
            rb.velocity = new Vector2( rb.velocity.x,10f);

        }
    }
}
